/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,html}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#2a2a2a',
        'on-secondary-fixed-variant': '#474746',
        'tertiary-fixed-dim': '#e5c460',
        'secondary-fixed': '#e4e2e1',
        'on-primary-fixed': '#241a00',
        'on-background': '#e5e2e1',
        'on-primary-container': '#554300',
        'tertiary-container': '#d0b04e',
        'surface-container-highest': '#353534',
        'tertiary-fixed': '#ffe087',
        'on-error': '#690005',
        'secondary-container': '#474746',
        'surface-container': '#201f1f',
        'inverse-primary': '#735c00',
        primary: '#f2ca50',
        error: '#ffb4ab',
        'surface-dim': '#131313',
        'error-container': '#93000a',
        'on-secondary': '#303030',
        'on-surface': '#e5e2e1',
        'primary-fixed': '#ffe088',
        'on-tertiary': '#3c2f00',
        'secondary-fixed-dim': '#c8c6c5',
        surface: '#131313',
        'inverse-on-surface': '#313030',
        outline: '#99907c',
        'on-secondary-fixed': '#1b1c1c',
        'outline-variant': '#4d4635',
        'surface-variant': '#353534',
        tertiary: '#edcc67',
        'surface-bright': '#393939',
        'on-surface-variant': '#d0c5af',
        'primary-fixed-dim': '#e9c349',
        'on-tertiary-container': '#554300',
        'on-tertiary-fixed': '#231a00',
        'surface-tint': '#e9c349',
        'inverse-surface': '#e5e2e1',
        'on-primary-fixed-variant': '#574500',
        'on-error-container': '#ffdad6',
        secondary: '#c8c6c5',
        'on-secondary-container': '#b6b5b4',
        'primary-container': '#d4af37',
        'surface-container-low': '#1c1b1b',
        background: '#131313',
        'on-primary': '#3c2f00',
        'on-tertiary-fixed-variant': '#574500',
        'surface-container-lowest': '#0e0e0e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '48px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        lg: '24px',
        gutter: '20px',
        sm: '8px',
        xs: '4px',
        unit: '4px',
        'container-max': '1280px',
        md: '16px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'display-lg': ['IBM Plex Sans', 'sans-serif'],
        'headline-md': ['IBM Plex Sans', 'sans-serif'],
        'body-md': ['Noto Sans', 'sans-serif'],
        'body-lg': ['Noto Sans', 'sans-serif'],
        'label-md': ['IBM Plex Sans', 'sans-serif'],
        caption: ['Noto Sans', 'sans-serif'],
        'headline-lg': ['IBM Plex Sans', 'sans-serif'],
        'headline-lg-mobile': ['IBM Plex Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
      },
      keyframes: {
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        fadeInUp: 'fadeInUp 1s ease-out both',
      },
    },
  },
  plugins: [],
}
